version: 2

jobs:
  setup:
    docker:
      - image: circleci/node:latest
    working_directory: ~/repo
    steps:
    - restore_cache:
        keys:
          - setup-{{ .Branch }}
          - setup-
    - checkout
    - run: npm install --no-optional --no-shrinkwrap --no-package-lock
    - save_cache:
        paths:
          - ".git"
          - node_modules
        key: setup-{{ .Branch }}

  test:
    docker:
      - image: circleci/node:latest
    working_directory: ~/repo
    steps:
    - restore_cache:
        keys:
          - setup-{{ .Branch }}
    - checkout
    - run: npm run test

  build:
    docker:
      - image: circleci/node:latest
    working_directory: ~/repo
    steps:
    - restore_cache:
        keys:
          - setup-{{ .Branch }}
    - checkout
    - run: npm run build
    - save_cache:
        paths:
          - docker/app
        key: build-{{ .Branch }}

  docker:
    machine: true
    working_directory: ~/repo
    steps:
      - restore_cache:
          keys:
            - build-{{ .Branch }}
      - run:
          name: Logging in to Docker
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: 
          name: Building image
          command: |
            cd ~/repo/docker/app
            docker build -t samerziadeh/phishing-flooder:latest .
      - run:
          name: Publishing image
          command: docker image push samerziadeh/phishing-flooder


workflows:
  version: 2

  setup-test-build-deploy:
    jobs:
      - setup
      - test:
          requires:
            - setup
      - build:
          requires:
            - test
      - docker:
          requires:
            - build