version: 2

jobs:
  setup-code:
    docker:
      - image: circleci/node:latest
    working_directory: ~/repo
    steps:
    - restore_cache:
        keys:
          - build-{{ .Branch }}
          - build-
    - checkout
    - run: npm install --no-optional --no-shrinkwrap --no-package-lock
    - save_cache:
        paths:
          - ".git"
          - node_modules
        key: build-{{ .Branch }}

  test-code:
    docker:
      - image: circleci/node:latest
    working_directory: ~/repo
    steps:
    - restore_cache:
        keys:
          - build-{{ .Branch }}
    - checkout
    - run: npm run test

  build-code:
    docker:
      - image: circleci/node:latest
    working_directory: ~/repo
    steps:
    - restore_cache:
        keys:
          - build-{{ .Branch }}
    - checkout
    - run: npm run build

  # build-docker:

workflows:
  version: 2

  setup_and_test:
    jobs:
      - setup-code
      - test-code
  build_code:
    requires:
      - setup_and_test
    jobs:
      - build-code
  # build_docker:
  #   requires:
  #     - setup_and_test
  #     - build_code
  #   jobs:
  #     - build-docker
