version: 2

jobs:
  setup-code:
    docker:
      - image: circleci/node:latest
    working_directory: ~/repo
    steps:
    - restore_cache:
        keys:
          - build-{{ .Branch }}
          - build-
    - checkout
    - run: npm install --no-optional --no-shrinkwrap --no-package-lock
    - save_cache:
        paths:
          - ".git"
          - node_modules
        key: build-{{ .Branch }}

  test-code:
    docker:
      - image: circleci/node:latest
    working_directory: ~/repo
    steps:
    - restore_cache:
        keys:
          - build-{{ .Branch }}
    - checkout
    - run: npm run test

  build-code:
    docker:
      - image: circleci/node:latest
    working_directory: ~/repo
    steps:
    - restore_cache:
        keys:
          - build-{{ .Branch }}
    - checkout
    - run: npm run build

  # build-docker:

workflows:
  version: 2

  setup-test-build-deploy:
    jobs:
      - setup-code
      - test-code:
          requires:
            - setup-code
      - build-code:
          requires:
            - setup-code
            - test-code
      # - build-docker:
      #     requires:
      #       - setup-code
      #       - test-code
      #       - build-code